#!/bin/bash

#---------------------------------------------------------------------------------
#	Architecture file for compiling and running CHIMERE	
#	Specify path to libraries, compilers and utilities 
#---------------------------------------------------------------------------------


#---------------------------------------------------------------------------------
# 	Compilers
#---------------------------------------------------------------------------------
export my_compilerF90=gfortran				# Path to Fortran 90 compiler
export my_compilerC=gcc				# Path to C compiler
export my_compilerCpp=g++				# Path to C++ compiler


#---------------------------------------------------------------------------------
# 	MPI - parallel execution of chimere
#---------------------------------------------------------------------------------
export  my_mpiframe=openmpi  			# implementaion of MPI norm [ ompi / ccrt ] TO REMOVE
export dirdir=/home/sibarra/chimere2020/libs
export  my_ompiparams="-mca btl self,sm,tcp -x LD_LIBRARY_PATH"

export  my_mpibin=${dirdir}/bin    			# Path to MPI binary directory
export  my_mpirun=${dirdir}/bin/mpirun   			# Path to mpirun to execute parallel job in MPI
export  my_mpif90=${dirdir}/bin/mpif90    			# Wrapper to my_compilerF90 to link with MPI library
export  my_mpicc=${dirdir}/bin/mpicc    			# Wrapper to my_compilerC to link with MPI library
export  my_mpilib=${dirdir}/lib    			# Path to MPI libraries directory
export  my_mpiinc=${dirdir}/include   			# Path to MPI include files directory


#---------------------------------------------------------------------------------
# 	HDF5  - parallel version	
#---------------------------------------------------------------------------------
export my_hdflib=${dirdir}/lib		# Path to HDF5 parallel library directory
export my_hdfinc=${dirdir}/include		# Path to HDF5 parallel include files directory


#---------------------------------------------------------------------------------
# 	NETCDF-C  - link with HDF5 parallel 
#---------------------------------------------------------------------------------
export my_netcdfCbin=${dirdir}/bin 		# Path to NETCDF-C (linked with HDF5 parallel) binaries directory 
export my_netcdfClib=${dirdir}/lib		# Path to NETCDF-C (linked with HDF5 parallel) library directory


#---------------------------------------------------------------------------------
# 	NETCDF-Fortran  - link with HDF5 parallel and NETCDF-C
#---------------------------------------------------------------------------------
export my_netcdfF90bin=${dirdir}/bin         # PATH to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) binaries  directory
export my_netcdfF90lib=${dirdir}/lib		# Path to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) library  directory
export my_netcdfF90inc=${dirdir}/include		# Path to NETCDF-Fortran (linked with HDF5 parallel and NETCDF-C) include files  directory


#---------------------------------------------------------------------------------
# 	GRIB  - link with jasper 
#---------------------------------------------------------------------------------
export my_griblib=${dirdir}/lib     			# Path to GRIB library directory
export my_gribinc=${dirdir}/include 			# Path to GRIB include files directory
export my_jasperlib=${dirdir}/lib 			# Path to JASPER library directory
export my_jasperinc=${dirdir}/include/jasper			# Path to JASPER include files directory


#---------------------------------------------------------------------------------
# 	BLITZ
#---------------------------------------------------------------------------------
export my_blitzinc=${dirdir}/include		 # Path to BLITZ include files 


#---------------------------------------------------------------------------------
# 	Utilities	
#---------------------------------------------------------------------------------
export my_make=make 		# Path to make 
export my_awk=awk			# Path to awk
export my_ncdump=${dirdir}/bin/ncdump		# Path to ncdump


#---------------------------------------------------------------------------------
# 	Makefile header needed to compile CHIMERE and WRF 
#	     - with this architecture configuration - 	
#---------------------------------------------------------------------------------
export my_hdr=Makefile.hdr.gfortran-64-ompi   			# Makefile header to compile CHIMERE in makefiles.hdr directory
export configure_wrf_file_name=configure.wrf.gfortran  	# Makefile header to compile WRF in config_wrf directory
export configure_wps_file_name=configure_gfortran.wps  	# Makefile header to compile WPS in config_wps directory


#---------------------------------------------------------------------------------
#	Export of Shared Library to be available at run time 	
#---------------------------------------------------------------------------------
export LD_LIBRARY_PATH=${my_hdflib}:${my_netcdfF90lib}:${my_netcdfClib}:${my_griblib}:${my_mpilib}:${my_mpilib}/openmpi:$LD_LIBRARY_PATH




